python:
  - 3.10
python_impl:
  - cpython
is_python_min:
  - no
numpy:
  - 1.16
# The build script links against Tcl/Tk 8.6 on this Python branch.
tk:
  - '8.6'
MACOSX_SDK_VERSION:            # [osx and x86_64]
  - 11.0                       # [osx and x86_64]
