{% set version = "2.7.15" %}

package:
  name: python
  version: {{ version }}

source:
  url: https://www.python.org/ftp/python/{{ version }}/Python-{{ version }}.tgz
  sha256: 18617d1f15a380a919d517630a9cd85ce17ea602f9bbdc58ddc672df4b0239db
  patches:
      - 0001-backport-Python-3.6-_PYTHON_SYSCONFIGDATA_NAME.patch
      - osx-dist.patch                  # [osx and x86_64]
      - win-find_exe.patch              # [win]
      - win-library_bin.patch           # [win]
      - 0008-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
      - 0017-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - PR_6724.patch

build:
  number: 0
  skip: True  # [win and vc!=9]
  no_link:
    - bin/python2.7     # [unix]
    - DLLs/_ctypes.pyd  # [win]
  script_env:
    - python_branding

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - bzip2             # [unix]
    - openssl           # [unix]
    - readline          # [unix]
    - sqlite            # [unix]
    - tk                # [unix]
    - zlib              # [unix]
    - ncurses           # [linux]
  run:
    - openssl           # [unix]
    - readline          # [unix]
    - sqlite            # [unix]
    - tk                # [unix]
    - zlib              # [unix]
    - ncurses           # [linux]
    - vs2008_runtime    # [win]

test:
  commands:
    - python -V
    - pydoc -h
    - python-config --help  # [unix]
    - idle -h

about:
  home: http://www.python.org/
  license: PSF
  license_file: LICENSE
  summary: General purpose programming language

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - pelson
