package:
  name: python
  version: 3.5.1

source:
  fn: Python-3.5.1.tgz
  url: https://www.python.org/ftp/python/3.5.1/Python-3.5.1.tgz
  md5: be78e48cdfc1a7ad90efff146dce6cfe
  patches:
    # - condaforge_version.patch
    # - unix_setup_dist.patch
    # set configuration options to use conda's available libraries
    - external_libraries.patch    # [win]

build:
  number: 2
  # Windows has issues updating python if conda is using files itself.
  # Copy rather than link.
  no_link:
    - DLLs/_ctypes.py   # [win]
    - bin/python

requirements:
  build:
    - bzip2 1.0.*
    - ncurses 5.9*      # [linux]
    - openssl 1.0*
    - readline 6.2*     # [unix]
    - sqlite
    - tk       8.6*
    - vc       14
    - xz
    - zlib 1.2*
  run:
    - bzip2 1.0.*
    - ncurses 5.9*      # [linux]
    - openssl 1.0*
    - readline 6.2*     # [unix]
    - sqlite
    - tk      8.6*
    - vc      14
    - xz
    - zlib 1.2*

test:
  commands:
    - python -V
    - python3 -V            # [unix]
    - 2to3 -h
    - pydoc -h
    - python3-config --help  # [unix]

about:
  home: http://www.python.org/
  license: PSF
  summary: General purpose programming language
      
extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - pelson
