package:
  name: python
  version: 1.0.1

source: 
  fn: python1.0.1.tar.gz
  url: http://legacy.python.org/download/releases/src/python1.0.1.tar.gz
  sha256: 1ce4167d0a297a6f9cc74f9b8da53ff359d872c18bf10e98563c7ba4a5f9893b
  patches:
    # Modules/fileobject.c defines a getline function which conflicts with the
    # one in stdio.h, rename the function in the file to _getline
    - fileobject_getline.patch

build:
  number: 0
  skip: True  # [win]
  # /lib/python uses a prefix to set the initial sys path, this needs to be
  # replace with the install prefix at installation
  detect_binary_files_with_prefix: True

test:
  commands:
    - python -c "import sys; print sys.path"
    # struct is a compiled module
    - python -c "import struct"
    # os is a python module, import will fail if sys.path is incorrect
    - python -c "import os"
    - python -c "import sys; print sys.version"

about:
  home: http://www.python.org/
  license: PSF
  summary: General purpose programming language
      
extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - pelson
