{% set version = "3.5.3" %}

package:
  name: python
  version: {{ version }}

source:
  fn: Python-{{ version }}.tgz
  url: https://www.python.org/ftp/python/{{ version }}/Python-{{ version }}.tgz
  sha256: 1524b840e42cf3b909e8f8df67c1724012c7dc7f9d076d4feef2d3eff031e8a0
  patches:
    - omit-local-site-packages.patch  # [osx]
    - osx64-dist.patch                # [osx and x86_64]
    - win-find_exe.patch              # [win]
    - win-library_bin.patch           # [win]
    # Adjust FD_SETSIZE to allow select() to wait on more connections
    # simultaneously.  Desirable for serious use of Tornado on Windows.
    # See also:
    # - https://bugs.python.org/issue28708
    # - https://github.com/zeromq/libzmq/issues/1165
    - fd_setsize.patch                # [win]

build:
  number: 5
  # Windows has issues updating python if conda is using files itself.
  # Copy rather than link.
  no_link:
    - DLLs/_ctypes.pyd  # [win]
    - bin/python3.5     # [unix]
  track_features:
    - vc14              # [win]
  script_env:
    - python_branding

requirements:
  build:
    - bzip2 1.0.*       # [unix]
    - openssl 1.0.*     # [unix]
    - readline 6.2*     # [unix]
    - sqlite 3.13.*     # [unix]
    - tk 8.5.*          # [unix]
    - xz 5.2.*          # [unix]
    - zlib 1.2.*        # [unix]
    - ncurses 5.9*      # [linux]
  run:
    - openssl 1.0.*     # [unix]
    - readline 6.2*     # [unix]
    - sqlite 3.13.*     # [unix]
    - tk 8.5.*          # [unix]
    - xz 5.2.*          # [unix]
    - zlib 1.2.*        # [unix]
    - ncurses 5.9*      # [linux]
    - vs2015_runtime    # [win]

test:
  commands:
    - python -V
    - python3 -V            # [unix]
    - 2to3 -h
    - pydoc -h
    - python3-config --help  # [unix]

about:
  home: http://www.python.org/
  license: PSF
  summary: General purpose programming language
      
extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - pelson
    - ocefpaf
