package:
  name: python
  version: 3.5.1

source:
  fn: Python-3.5.1.tgz
  url: https://www.python.org/ftp/python/3.5.1/Python-3.5.1.tgz
  sha256: 687e067d9f391da645423c7eda8205bae9d35edc0c76ef5218dcbe4cc770d0d7
  patches:
    # Apply OS X patch from MacPorts
    - omit-local-site-packages.patch  # [osx]
    - patch-Lib-ctypes-macholib-dyld.py.diff  # [osx]
    - patch-configure.diff  # [osx]
    - patch-setup.py.diff  # [osx]
    # These patch are MacPort specific and not needed
    #- patch-Lib-cgi.py.diff  # [osx]
    #- patch-setup.py-disabled_modules.diff  # [osx]
    #- patch-libedit.diff  # [osx]

build:
  number: 1  # [osx]
  number: 0  # [linux]
  number: 0  # [win]
  # Windows has issues updating python if conda is using files itself.
  # Copy rather than link.
  no_link:
    - DLLs/_ctypes.py   # [win]
    - bin/python
  track_features:
    - vc14              # [win]

requirements:
  build:
    - bzip2 1.0.*       # [unix]
    - zlib 1.2*         # [unix]
    - sqlite 3.9.*      # [unix]
    - readline 6.2*     # [unix]
    - tk 8.5*           # [unix]
    - openssl 1.0*      # [unix]
    - xz 5.0.*          # [unix]
    - ncurses 5.9*      # [linux]
  run:
    - zlib 1.2*         # [unix]
    - sqlite 3.9.*      # [unix]
    - readline 6.2*     # [unix]
    - tk 8.5*           # [unix]
    - openssl 1.0*      # [unix]
    - xz 5.0.*          # [unix]
    - ncurses 5.9*      # [linux]

test:
  commands:
    - python -V
    - python3 -V            # [unix]
    - 2to3 -h
    - pydoc -h
    - python3-config --help  # [unix]

about:
  home: http://www.python.org/
  license: PSF
  summary: General purpose programming language
      
extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - pelson
