{% set version = "3.7.0" %}

package:
  name: python
  version: {{ version }}

source:
  url: https://www.python.org/ftp/python/{{ version }}/Python-{{ version }}.tgz
  sha256: 85bb9feb6863e04fb1700b018d9d42d1caac178559ffa453d7e6a436e259fd0d
  patches:
    - osx64-dist.patch                # [osx and x86_64]
    - win-find_exe.patch              # [win]
    - win-library_bin.patch           # [win]
    # Adjust FD_SETSIZE to allow select() to wait on more connections
    # simultaneously.  Desirable for serious use of Tornado on Windows.
    # See also:
    # - https://bugs.python.org/issue28708
    # - https://github.com/zeromq/libzmq/issues/1165
    - fd_setsize.patch                # [win]
    - mingw-w64--DMS_WINXX.patch
    - win-msc_ver-1900.patch
    - do-not-download-externals.patch  # [win]
    - 0015-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
    - winsdk.patch  # [win]

build:
  number: 0
  # Windows has issues updating python if conda is using files itself.
  # Copy rather than link.
  no_link:
    - DLLs/_ctypes.pyd  # [win]
    - bin/python3.7     # [unix]
  #track_features:
    #- vc14              # [win]
  script_env:
    - python_branding
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - 7za               # [win]
    - curl              # [win]
  host:
    - nasm 2.11.06      # [win]
    - bzip2             # [unix]
    - openssl           # [unix]
    - readline          # [unix]
    - sqlite            # [unix]
    - tk                # [unix]
    - xz                # [unix]
    - zlib              # [unix]
    - ncurses           # [linux]
    - libffi            # [unix]
  run:
    - openssl           # [unix]
    - readline          # [unix]
    - sqlite            # [unix]
    - tk                # [unix]
    - xz                # [unix]
    - zlib              # [unix]
    - ncurses           # [linux]
    - libffi            # [unix]
    #- vs2015_runtime    # [win]

test:
  commands:
    - python -V
    - python3 -V            # [unix]
    - 2to3 -h
    - pydoc -h
    - python3-config --help  # [unix]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.python.org/
  license: PSF
  license_file: LICENSE
  summary: 'General purpose programming language.'

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - pelson
    - ocefpaf
