{% set version = "2.7.14" %}
{% set sha256 = "304c9b202ea6fbd0a4a8e0ad3733715fbd4749f2204a9173a58ec53c32ea73e8" %}

package:
  name: python
  version: {{ version }}

source:
  fn: Python-{{ version }}.tgz
  url: https://www.python.org/ftp/python/{{ version }}/Python-{{ version }}.tgz
  sha256: {{ sha256 }}
  patches:
      - osx-dist.patch                  # [osx and x86_64]
      - win-find_exe.patch              # [win]
      - win-library_bin.patch           # [win]
      - 0008-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
      - 0017-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
build:
  number: 4
  no_link:
    - bin/python2.7     # [unix]
    - DLLs/_ctypes.pyd  # [win]
  track_features:
    - vc9               # [win]
  script_env:
    - python_branding

requirements:
  build:
    - bzip2 1.0.*       # [unix]
    - openssl 1.0.*     # [unix]
    - readline 7.0      # [unix]
    - sqlite 3.20.*     # [unix]
    - tk 8.6.*          # [unix]
    - zlib 1.2.11       # [unix]
    - ncurses 5.9       # [linux]
  run:
    - openssl 1.0.*     # [unix]
    - readline 7.0      # [unix]
    - sqlite 3.20.*     # [unix]
    - tk 8.6.*          # [unix]
    - zlib 1.2.11       # [unix]
    - ncurses 5.9*      # [linux]
    - vs2008_runtime    # [win]

test:
  commands:
    - python -V
    - pydoc -h
    - python-config --help  # [unix]
    - idle -h
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.python.org/
  license: PSF
  license_file: LICENSE
  summary: General purpose programming language

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - pelson
