package:
  name: python
  version: 1.3

source: 
  fn: python-1.3.tar.gz
  url: http://legacy.python.org/download/releases/src/python-1.3.tar.gz
  sha256: 892a12d7360b5e6aed0f6a637f5dbdd4ea9a27ee0e2741337393b1d5711d2d33
  patches:
    # Modules/fileobject.c defines a getline function which conflicts with the
    # one in stdio.h, rename the function in the file to _getline
    - fileobject_getline.patch
    # The crypt library needs to be linked when compiling python
    - setup.in_lcrypt.patch  # [not osx]


build:
  number: 0
  skip: True  # [win]
  # /lib/python uses a prefix to set the initial sys path, this needs to be
  # replace with the install prefix at installation
  detect_binary_files_with_prefix: True

test:
  commands:
    - python -c "import sys; print sys.path"
    # struct is a compiled module
    - python -c "import struct"
    # os is a python module, import will fail if sys.path is incorrect
    - python -c "import os"
    - python -c "import sys; print sys.version"

about:
  home: http://www.python.org/
  license: PSF
  summary: General purpose programming language
      
extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - pelson
