package:
  name: python
  version: 2.7.12

source:
  fn: Python-2.7.12.tgz
  url: https://www.python.org/ftp/python/2.7.12/Python-2.7.12.tgz
  sha256: 3cb522d17463dfa69a155ab18cffa399b358c966c0363d6c8b5b3bf1384da4b6
  patches:
      - omit-local-site-packages.patch  # [osx]

build:
  number: 0
  # Windows has issues updating python if conda is using files itself.
  # Copy rather than link.
  no_link:
    - DLLs/_ctypes.py   # [win]
    - bin/python
  track_features:
    - vc9               # [win]

requirements:
  build:
    - bzip2 1.0.*       # [unix]
    - openssl 1.0.*     # [unix]
    - readline 6.2*     # [unix]
    - sqlite 3.9.*      # [unix]
    - tk 8.5.*          # [unix]
    - zlib 1.2.*        # [unix]
    - ncurses 5.9*      # [linux]
  run:
    - openssl 1.0.*     # [unix]
    - readline 6.2*     # [unix]
    - sqlite 3.9.*      # [unix]
    - tk 8.5.*          # [unix]
    - zlib 1.2.*        # [unix]
    - ncurses 5.9*      # [linux]

test:
  commands:
    - python -V
    - pydoc -h
    - python-config --help  # [unix]
    - idle -h

about:
  home: http://www.python.org/
  license: PSF
  summary: General purpose programming language
      
extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - pelson
