package:
  name: python
  version: 3.6.0a1

source:
  fn: Python-3.6.0a1.tgz
  url: https://www.python.org/ftp/python/3.6.0/Python-3.6.0a1.tgz
  md5: 205e1424c57c1779069b5f9301c1ab48

build:
  number: 1
  # Windows has issues updating python if conda is using files itself.
  # Copy rather than link.
  no_link:
    - DLLs/_ctypes.py   # [win]
    - bin/python
  track_features:
    - vc14              # [win]

requirements:
  build:
    - conda-forge-build-setup   # Used to set condarc correctly
    - bzip2 1.0.*       # [unix]
    - openssl 1.0.*     # [unix]
    - readline 6.2*     # [unix]
    - sqlite 3.13.*     # [unix]
    - tk 8.5.*          # [unix]
    - xz 5.2.*          # [unix]
    - zlib 1.2.*        # [unix]
    - ncurses 5.9*      # [linux]
  run:
    - openssl 1.0.*     # [unix]
    - readline 6.2*     # [unix]
    - sqlite 3.13.*     # [unix]
    - tk 8.5.*          # [unix]
    - xz 5.2.*          # [unix]
    - zlib 1.2.*        # [unix]
    - ncurses 5.9*      # [linux]

test:
  commands:
    - python -V
    - python3 -V            # [unix]
    - 2to3 -h
    - pydoc -h
    - python3-config --help  # [unix]

about:
  home: http://www.python.org/
  license: PSF
  summary: General purpose programming language
      
extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - pelson
