package:
  name: python
  version: 2.0

source: 
  fn: python-2.0.tar.gz
  url: http://legacy.python.org/download/releases/src/python-2.0.tar.gz
  sha256: 63bbcb1a69cd1673b92068247ba0fba19a2b3ddcb7b73bc9391fa148b3d4e652
  patches:
    # OS X uses a file insensitive filesystem so the python binary is not
    # copied out of the Python directory, adjust the Makefile for this
    - Makefile.in_python_path.patch  # [osx]

build:
  number: 0
  skip: True  # [win]
  # /lib/python uses a prefix to set the initial sys path, this needs to be
  # replace with the install prefix at installation
  detect_binary_files_with_prefix: True

test:
  commands:
    - python -c "import sys; print sys.version"
    - python2.0 -c "import sys; print sys.version"
    - python -c "import sys; print sys.path"
    # struct is a compiled module
    - python -c "import struct"
    # os is a python module, import will fail if sys.path is incorrect
    - python -c "import os"

about:
  home: http://www.python.org/
  license: PSF
  summary: General purpose programming language
      
extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - pelson
