build_platform: {osx_arm64: osx_64}
conda_forge_output_validation: true
provider: {linux_aarch64: native, linux_ppc64le: native, osx: azure, win: azure}
test_on_native_only: true
bot:
  abi_migration_branches:
    - 3.6
    - 3.7
    - 3.8
