build_platform: {osx_arm64: osx_64, linux_ppc64le: linux_64, linux_aarch64: linux_64}
conda_forge_output_validation: true
provider: {linux_aarch64: default, linux_ppc64le: native}
bot:
  abi_migration_branches:
  - '3.8'
  - '3.9'
  - '3.10'
  - '3.11'
  - '3.12'
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
test: native_and_emulated
