azure:
  store_build_artifacts: true
bot:
  abi_migration_branches:
  - '3.8'
  - '3.9'
  - '3.10'
  - '3.11'
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
  win_arm64: win_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
  linux_ppc64le: native
test: native_and_emulated
