build_platform: {osx_arm64: osx_64}
conda_forge_output_validation: true
provider: {linux_aarch64: default, linux_ppc64le: native}
bot:
  abi_migration_branches:
  - 3.7
  - 3.8
  - 3.9
azure:
  store_build_artifacts: true
conda_build:
  pkg_format: '2'
test: native_and_emulated
