azure:
  store_build_artifacts: true
bot:
  abi_migration_branches:
  - 3.7
  - 3.8
  - 3.9
build_platform:
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
  linux_ppc64le: native
remote_ci_setup:
- conda-forge-ci-setup=3
- libsolv<0.7.23
test: native_and_emulated
test_on_native_only: true
