build_platform: {osx_arm64: osx_64}
conda_forge_output_validation: true
provider: {linux_aarch64: azure, linux_ppc64le: native, osx: azure, win: azure}
bot:
  abi_migration_branches:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
test: native_and_emulated
