compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure, osx: circle}
channels:
  targets:
  - [conda-forge, pre-3.8]
conda_forge_output_validation: true
conda_build:
  pkg_format: '2'
